import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster";
import getSongsByUserId from "@/actions/getSongsByUserId";
import Player from "@/components/Player";
import ModalProvider from "@/provider/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const revalidate = 0;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSongs = await getSongsByUserId();

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ModalProvider />
        <Sidebar songs={userSongs}>{children}</Sidebar>
        <Toaster />
        <Player />
      </body>
    </html>
  );
}
